using Engine.Core;
using NATS.Client.Core;

namespace Engine.Client;

/// <summary>
/// Client-side proxy for a single entity.
/// Behaviour operations are forwarded to the backend over NATS request-reply.
/// </summary>
public sealed class Entity
{
    private readonly INatsConnection _nats;

    public EntityId Id { get; }

    /// <summary>
    /// The NATS connection used by this entity for behaviour proxies.
    /// </summary>
    public INatsConnection Nats => _nats;

    public Entity(EntityId id, INatsConnection nats)
    {
        Id = id;
        _nats = nats;
    }

    /// <summary>
    /// Registers a behaviour on this entity via the backend.
    /// </summary>
    public async Task AddBehaviourAsync<TBehaviour>(CancellationToken ct = default)
        where TBehaviour : IBehaviour
    {
        var payload = $"{Id.Value}:{BehaviourName<TBehaviour>()}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.add-behaviour",
            payload,
            cancellationToken: ct
        );

        if (reply.Data is not "ok")
            throw new InvalidOperationException(
                $"Failed to add behaviour {BehaviourName<TBehaviour>()} to entity {Id}: {reply.Data}"
            );
    }

    /// <summary>
    /// Removes a behaviour from this entity via the backend.
    /// </summary>
    public async Task RemoveBehaviourAsync<TBehaviour>(CancellationToken ct = default)
        where TBehaviour : IBehaviour
    {
        var payload = $"{Id.Value}:{BehaviourName<TBehaviour>()}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.remove-behaviour",
            payload,
            cancellationToken: ct
        );

        if (reply.Data is not "ok")
            throw new InvalidOperationException(
                $"Failed to remove behaviour {BehaviourName<TBehaviour>()} from entity {Id}: {reply.Data}"
            );
    }

    /// <summary>
    /// Checks whether this entity has a given behaviour via the backend.
    /// </summary>
    public async Task<bool> HasBehaviourAsync<TBehaviour>(CancellationToken ct = default)
        where TBehaviour : IBehaviour
    {
        var payload = $"{Id.Value}:{BehaviourName<TBehaviour>()}";
        var reply = await _nats.RequestAsync<string, string>(
            "entity.has-behaviour",
            payload,
            cancellationToken: ct
        );

        return reply.Data is "true";
    }

    /// <summary>
    /// Lists all behaviour names attached to this entity.
    /// </summary>
    public async Task<IReadOnlyList<string>> ListBehavioursAsync(CancellationToken ct = default)
    {
        var reply = await _nats.RequestAsync<string, string>(
            "entity.list-behaviours",
            Id.Value.ToString(),
            cancellationToken: ct
        );

        if (string.IsNullOrEmpty(reply.Data))
            return Array.Empty<string>();

        return reply.Data!.Split(',');
    }

    /// <summary>
    /// Returns a client-side proxy for the given behaviour interface.
    /// The proxy type is resolved by convention: the interface name with the leading 'I' stripped
    /// and "Proxy" appended (e.g., <c>IPose</c> → <c>PoseProxy</c>), generated by Engine.Generators.
    /// Searches all loaded assemblies because proxy types are generated in module projects.
    /// </summary>
    public TBehaviour GetBehaviour<TBehaviour>()
        where TBehaviour : IBehaviour
    {
        var interfaceType = typeof(TBehaviour);
        var interfaceName = interfaceType.Name;
        var proxyName =
            interfaceName.Length > 1 && interfaceName[0] == 'I' && char.IsUpper(interfaceName[1])
                ? interfaceName.Substring(1) + "Proxy"
                : interfaceName + "Proxy";

        var qualifiedName = $"{interfaceType.Namespace}.{proxyName}";

        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies())
        {
            var proxyType = assembly.GetType(qualifiedName);
            if (proxyType is not null && interfaceType.IsAssignableFrom(proxyType))
                return (TBehaviour)Activator.CreateInstance(proxyType, Id, _nats)!;
        }

        throw new InvalidOperationException(
            $"No generated proxy type '{proxyName}' found for behaviour '{interfaceName}'. "
                + "Ensure Engine.Generators is referenced as an analyzer in the module project."
        );
    }

    /// <summary>
    /// Derives the canonical behaviour name from the type parameter.
    /// </summary>
    private static string BehaviourName<TBehaviour>()
        where TBehaviour : IBehaviour => typeof(TBehaviour).Name;
}
