using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Engine.Generators;

/// <summary>
/// Emits partial classes for <c>ComponentBase&lt;TContract&gt;</c> subclasses.
/// Each partial class adds:
/// <list type="bullet">
///   <item>The contract interface (e.g., <c>: IPose</c>)</item>
///   <item><c>DataUpdated</c> and <c>DataRemoved</c> events</item>
///   <item><c>RaiseUpdated</c> and <c>RaiseRemoved</c> protected methods</item>
/// </list>
/// </summary>
internal static class ComponentEmitter
{
    public static void Emit(
        SourceProductionContext context,
        ImmutableArray<ComponentImplInfo> implementations
    )
    {
        if (implementations.IsDefaultOrEmpty)
            return;

        foreach (var impl in implementations.Distinct())
        {
            var source = GeneratePartial(impl);
            context.AddSource($"{impl.ClassName}.g.cs", source);
        }
    }

    private static string GeneratePartial(ComponentImplInfo impl)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        sb.AppendLine("using Engine.Core;");
        sb.AppendLine();

        if (impl.Namespace is not null)
        {
            sb.AppendLine($"namespace {impl.Namespace};");
            sb.AppendLine();
        }

        sb.AppendLine($"/// <summary>");
        sb.AppendLine(
            $"/// Generated partial class — adds the <see cref=\"{impl.ContractInterfaceName}\"/> interface"
        );
        sb.AppendLine($"/// and event infrastructure for <see cref=\"{impl.ClassName}\"/>.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {impl.ClassName} : {impl.FullyQualifiedContractName}");
        sb.AppendLine("{");

        // Events
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine(
            $"    public event Action<Entity, {impl.FullyQualifiedDataType}>? DataUpdated;"
        );
        sb.AppendLine();
        sb.AppendLine($"    /// <inheritdoc />");
        sb.AppendLine($"    public event Action<Entity>? DataRemoved;");
        sb.AppendLine();

        // RaiseUpdated
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine(
            $"    /// Call this from <see cref=\"SetAsync\"/> after a successful write to fire the"
        );
        sb.AppendLine($"    /// <see cref=\"DataUpdated\"/> event.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine(
            $"    protected void RaiseUpdated(Entity entity, {impl.FullyQualifiedDataType} data)"
        );
        sb.AppendLine("    {");
        sb.AppendLine("        DataUpdated?.Invoke(entity, data);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // RaiseRemoved
        sb.AppendLine($"    /// <summary>");
        sb.AppendLine(
            $"    /// Call this from <see cref=\"IComponent.OnRemoveAsync\"/> after successful cleanup to fire the"
        );
        sb.AppendLine($"    /// <see cref=\"DataRemoved\"/> event.");
        sb.AppendLine($"    /// </summary>");
        sb.AppendLine($"    protected void RaiseRemoved(Entity entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        DataRemoved?.Invoke(entity);");
        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }
}
